name: 'main'

on:
  push:
  schedule:
    - cron: '30 5 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Run main.sh' # 步骤二，执行sh命令文件
        run: echo helloworld # 运行命令。（注意，运行目录是仓库根目录）
